# Generated by Django 6.0.1 on 2026-02-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquipamento', models.CharField(max_length=100)),
                ('numeroEquipamento', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Indisponivel', 'Indisponivel'), ('Manutencao', 'Manutencao')], default='Novo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=100)),
                ('cpfCliente', models.CharField(blank=True, max_length=14, null=True)),
                ('dataLocacao', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkpoint.equipamentos')),
            ],
        ),
    ]
