# Generated by Django 6.0.2 on 2026-02-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquipamento', models.CharField(max_length=100)),
                ('numeroEquipamento', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Indisponivel', 'Indisponivel'), ('Manutencao', 'Manutencao')], default='Novo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=12)),
                ('cpf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataLocacao', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkpoint.equipamentos')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkpoint.usuarios')),
            ],
        ),
    ]
